Repository ZenBit-Tech/Codecrafter_mobile, pull requests merged in 2024-12, with the labels that each got.

#5 SCRUM-79-Verification-Screen
  .eslintrc.cjs
  package-lock.json
  package.json
  src/api/userActions.ts
  src/pages/NotFound/index.tsx
  src/pages/NotFound/styles.ts
  src/pages/SignIn/index.tsx
  src/pages/SignIn/useSignIn.ts
  src/pages/VerificationPage/components/BackButton/index.tsx
  src/pages/VerificationPage/components/BackButton/styles.ts
  src/pages/VerificationPage/components/OTPInputSection/index.tsx
  src/pages/VerificationPage/components/OTPInputSection/styles.ts
  src/pages/VerificationPage/components/ResendLink/index.tsx
  src/pages/VerificationPage/components/ResendLink/styles.ts
  src/pages/VerificationPage/components/TitleSection/index.tsx
  src/pages/VerificationPage/components/TitleSection/styles.ts
  src/pages/VerificationPage/index.tsx
  src/pages/VerificationPage/styles.ts
  src/pages/VerificationPage/useVerification.ts
  src/routes/ProtectedRoute.tsx
  src/routes/RestrictedRoute.tsx
  src/routes/router.tsx
  src/theme.ts
  src/utils/axiosInstance.ts
  src/utils/i18n.ts
Labels: enhancement

#7 Scrum 103 FE route details page
  .env.example
  package-lock.json
  package.json
  src/components/CustomCalendar/components/CalendarHeader/index.tsx
  src/constants/colors.ts
  src/constants/status.ts
  src/pages/OrderPage/styles.ts
  src/pages/RouteDetails/components/AddressList/index.tsx
  src/pages/RouteDetails/components/AddressList/styles.ts
  src/pages/RouteDetails/components/RoutingControl/index.tsx
  src/pages/RouteDetails/components/StatusIcon/index.tsx
  src/pages/RouteDetails/index.tsx
  src/pages/RouteDetails/styles.css
  src/pages/RouteDetails/styles.ts
  src/pages/RouteDetails/useDottedLine.ts
  src/routes/RestrictedRoute.tsx
  src/routes/router.tsx
  src/types/route.ts
  src/utils/i18n.ts
Labels: enhancement

#9 feat: connected FE to BE
  src/api/routeActions.ts
  src/api/userActions.ts
  src/components/Loader/index.tsx
  src/components/Loader/styles.ts
  src/constants/colors.ts
  src/constants/status.ts
  src/main.tsx
  src/pages/RouteDetails/components/AddressList/index.tsx
  src/pages/RouteDetails/components/AddressPlaceholder/index.tsx
  src/pages/RouteDetails/components/AddressPlaceholder/styles.ts
  src/pages/RouteDetails/components/FitBounds/index.tsx
  src/pages/RouteDetails/components/RoutingControl/index.tsx
  src/pages/RouteDetails/components/StatusIcon/index.tsx
  src/pages/RouteDetails/hooks/useDottedLine.ts
  src/pages/RouteDetails/hooks/useFetchRoute.ts
  src/pages/RouteDetails/hooks/useProcessAddresses.ts
  src/pages/RouteDetails/index.tsx
  src/pages/RouteDetails/utils/calculateDistance.ts
  src/redux/persistConfig.ts
  src/redux/slices/authSlice.ts
  src/redux/slices/routeSlice.ts
  src/redux/store.ts
  src/types/route.ts
  src/utils/i18n.ts
Labels: enhancement

#10 Feat/failed reasons
  src/components/Button/index.tsx
  src/constants/colors.ts
  src/constants/constants.ts
  src/constants/font.ts
  src/interfaces/FailedReason/index.ts
  src/pages/FailedReason/index.tsx
  src/pages/FailedReason/styles.ts
  src/pages/FailedReason/useFailedReason.ts
  src/pages/RouteDetails/components/FitBounds/index.tsx
  src/pages/RouteDetails/hooks/useFetchRoute.ts
  src/pages/RouteDetails/hooks/useProcessAddresses.ts
  src/routes/router.tsx
  src/theme.ts
  src/utils/i18n.ts
Labels: enhancement

#13 Feat/boarding pass
  .husky/pre-commit
  package-lock.json
  package.json
  src/components/Header/index.tsx
  src/constants/colors.ts
  src/constants/dateFormats.ts
  src/constants/font.ts
  src/constants/status.ts
  src/constants/styles.css
  src/hooks/useToggleVisible.ts
  src/interfaces/Customer/index.ts
  src/main.tsx
  src/pages/FailedReason/styles.ts
  src/pages/PickUpTheOrder/BoardingPass/BoardingPassVerificationPage/components/ActionBtns/index.tsx
  src/pages/PickUpTheOrder/BoardingPass/BoardingPassVerificationPage/components/ActionBtns/styles.ts
  src/pages/PickUpTheOrder/BoardingPass/BoardingPassVerificationPage/components/ActionBtns/useVerifyRequest.ts
  src/pages/PickUpTheOrder/BoardingPass/BoardingPassVerificationPage/components/BoardingPassInformBlock/components/TicketModal/index.tsx
  src/pages/PickUpTheOrder/BoardingPass/BoardingPassVerificationPage/components/BoardingPassInformBlock/components/TicketModal/styles.ts
  src/pages/PickUpTheOrder/BoardingPass/BoardingPassVerificationPage/components/BoardingPassInformBlock/index.tsx
  src/pages/PickUpTheOrder/BoardingPass/BoardingPassVerificationPage/components/BoardingPassInformBlock/styles.ts
  src/pages/PickUpTheOrder/BoardingPass/BoardingPassVerificationPage/components/BoardingPassInformBlock/useGetOrder.ts
  src/pages/PickUpTheOrder/BoardingPass/BoardingPassVerificationPage/index.tsx
  src/pages/PickUpTheOrder/BoardingPass/BoardingPassVerificationPage/useVerifyBoardingPass.ts
  src/pages/PickUpTheOrder/BoardingPass/IdentityVerification/components/ActionBtns/index.tsx
  src/pages/PickUpTheOrder/BoardingPass/IdentityVerification/components/ActionBtns/styles.ts
  src/pages/PickUpTheOrder/BoardingPass/IdentityVerification/components/CustomerInformBlock/index.tsx
  src/pages/PickUpTheOrder/BoardingPass/IdentityVerification/components/CustomerInformBlock/styles.css
  src/pages/PickUpTheOrder/BoardingPass/IdentityVerification/components/CustomerInformBlock/styles.ts
  src/pages/PickUpTheOrder/BoardingPass/IdentityVerification/components/CustomerInformBlock/useGetCustomerInform.ts
  src/pages/PickUpTheOrder/BoardingPass/IdentityVerification/index.tsx
  src/pages/PickUpTheOrder/BoardingPass/PreArrivalPage/components/ActionBtns/index.tsx
  src/pages/PickUpTheOrder/BoardingPass/PreArrivalPage/components/ActionBtns/styles.ts
  src/pages/PickUpTheOrder/BoardingPass/PreArrivalPage/components/CheckList/index.tsx
  src/pages/PickUpTheOrder/BoardingPass/PreArrivalPage/components/CheckList/styles.ts
  src/pages/PickUpTheOrder/BoardingPass/PreArrivalPage/index.tsx
  src/routes/router.tsx
  src/utils/i18n.ts
Labels: enhancement

#15 feat: SCRUM-152 added modal window and updated route details page
  .env.example
  .eslintrc.cjs
  src/components/Modal/index.tsx
  src/components/Modal/styles.ts
  src/constants/constants.ts
  src/pages/RouteDetails/components/AddressList/index.tsx
  src/pages/RouteDetails/components/RoutingControl/index.tsx
  src/pages/RouteDetails/components/StartTheRouteModal/index.tsx
  src/pages/RouteDetails/components/StartTheRouteModal/styles.ts
  src/pages/RouteDetails/hooks/useProcessAddresses.ts
  src/pages/RouteDetails/index.tsx
  src/pages/RouteDetails/utils/calculateDistance.ts
  src/theme.ts
  src/utils/i18n.ts
Labels: bug, documentation, enhancement

#16 feat: SCRUM-155 added modal dropdown for map
  .env.example
  src/constants/colors.ts
  src/constants/status.ts
  src/pages/RouteDetails/components/FitBounds/index.tsx
  src/pages/RouteDetails/components/MapView/index.tsx
  src/pages/RouteDetails/components/MapView/styles.ts
  src/pages/RouteDetails/components/StatusIcon/index.tsx
  src/pages/RouteDetails/hooks/useFetchAndProcessRoute.ts
  src/pages/RouteDetails/index.tsx
  src/pages/RouteDetails/styles.css
  src/pages/RouteDetails/styles.ts
  src/utils/i18n.ts
Labels: bug, documentation, enhancement

#22 Feat/get luggages
  package-lock.json
  package.json
  src/assets/icons/prohibiten-items.svg
  src/pages/PickUpTheOrder/BaggageCheck/BaggageCheckPage/components/ActionBtns/index.tsx
  src/pages/PickUpTheOrder/BaggageCheck/BaggageCheckPage/components/ActionBtns/styles.ts
  src/pages/PickUpTheOrder/BaggageCheck/BaggageCheckPage/components/CheckBaggageBlock/index.tsx
  src/pages/PickUpTheOrder/BaggageCheck/BaggageCheckPage/components/CheckBaggageBlock/styles.ts
  src/pages/PickUpTheOrder/BaggageCheck/BaggageCheckPage/index.tsx
  src/pages/PickUpTheOrder/BaggageCheck/CustomerConfirmation/components/ActionBtns/index.tsx
  src/pages/PickUpTheOrder/BaggageCheck/CustomerConfirmation/components/ActionBtns/styles.ts
  src/pages/PickUpTheOrder/BaggageCheck/CustomerConfirmation/components/CustomerConfirmationBlock/index.tsx
  src/pages/PickUpTheOrder/BaggageCheck/CustomerConfirmation/components/CustomerConfirmationBlock/styles.ts
  src/pages/PickUpTheOrder/BaggageCheck/CustomerConfirmation/index.tsx
  src/pages/PickUpTheOrder/BaggageCheck/ProhibitedItemsPage/components/ActionBtns/index.tsx
  src/pages/PickUpTheOrder/BaggageCheck/ProhibitedItemsPage/components/ActionBtns/styles.ts
  src/pages/PickUpTheOrder/BaggageCheck/ProhibitedItemsPage/components/ItemsBlock/index.tsx
  src/pages/PickUpTheOrder/BaggageCheck/ProhibitedItemsPage/components/ItemsBlock/styles.ts
  src/pages/PickUpTheOrder/BaggageCheck/ProhibitedItemsPage/index.tsx
  src/pages/PickUpTheOrder/BoardingPass/BoardingPassVerificationPage/components/ActionBtns/index.tsx
  src/pages/PickUpTheOrder/BoardingPass/PreArrivalPage/index.tsx
  src/routes/router.tsx
  src/utils/i18n.ts
Labels: enhancement

#23 feat: SCRUM-154 connected FE start the route to BE
  src/api/routeActions.ts
  src/constants/dateFormats.ts
  src/constants/statusCode.ts
  src/pages/RouteDetails/components/RouteActionButtons/index.tsx
  src/pages/RouteDetails/components/RouteActionButtons/styles.ts
  src/pages/RouteDetails/components/StartTheRouteModal/index.tsx
  src/pages/RouteDetails/components/StatusIcon/index.tsx
  src/pages/RouteDetails/hooks/useFetchRoute.ts
  src/pages/RouteDetails/hooks/useProcessAddresses.ts
  src/pages/RouteDetails/hooks/useUpdateRouteStatus.ts
  src/pages/RouteDetails/index.tsx
  src/pages/RouteDetails/styles.ts
  src/redux/slices/routeSlice.ts
  src/utils/i18n.ts
Labels: enhancement

#25 feat: add NavigateButton and NavigateButtonModal components with i18n…
  src/components/NavigateButton/index.tsx
  src/components/NavigateButton/styles.ts
  src/components/NavigateButtonModal/index.tsx
  src/components/NavigateButtonModal/styles.ts
  src/interfaces/Modal/index.ts
  src/pages/RouteDetails/components/RouteActionButtons/index.tsx
  src/pages/RouteDetails/components/StartTheRouteModal/index.tsx
  src/utils/i18n.ts
Labels: enhancement

#27 feat:Scrum-194 FE connect route and route details
  src/api/routeActions.ts
  src/pages/RouteDetails/hooks/useFetchAndProcessRoute.ts
  src/pages/RouteDetails/hooks/useFetchRoute.ts
  src/pages/RouteDetails/index.tsx
  src/pages/RoutesPage/components/RouteItem/index.tsx
  src/redux/persistConfig.ts
  src/redux/slices/authSlice.ts
  src/redux/slices/routeSlice.ts
  src/utils/axiosInstance.ts
  src/utils/i18n.ts
Labels: enhancement

#31 + Create: Personal profile page
  .eslintrc.cjs
  src/components/Header/index.tsx
  src/components/ProfilePicture/index.tsx
  src/constants/styles.css
  src/pages/PersonalProfile/index.tsx
  src/pages/PersonalProfile/styles.ts
  src/routes/router.tsx
Labels: enhancement

#30 Feat/jest setup
  .prettierignore
  jest.config.ts
  package-lock.json
  package.json
  src/test/componentForTest/Person.css
  src/test/componentForTest/Person.test.tsx
  src/test/componentForTest/Person.tsx
  tsconfig.json
Labels: enhancement

#28 Feat/notifications page
  .prettierrc
  README.md
  index.html
  src/assets/icons/bell-notification.svg
  src/assets/icons/luggage-notification.svg
  src/assets/icons/map-pin.svg
  src/assets/icons/route-notificaton.svg
  src/constants/numbers.ts
  src/constants/styles.css
  src/pages/MainPage/components/FooterNavigation/index.tsx
  src/pages/MainPage/components/FooterNavigation/useGetUnreadNotifications.ts
  src/pages/MainPage/components/Tab/index.tsx
  src/pages/MainPage/components/Tab/styles.ts
  src/pages/NotificationsPage/components/NotificationsBlock/components/BellNotification/index.tsx
  src/pages/NotificationsPage/components/NotificationsBlock/components/BellNotification/styles.ts
  src/pages/NotificationsPage/components/NotificationsBlock/components/ListOfNotes/index.tsx
  src/pages/NotificationsPage/components/NotificationsBlock/components/LuggageNotification/index.tsx
  src/pages/NotificationsPage/components/NotificationsBlock/components/LuggageNotification/styles.ts
  src/pages/NotificationsPage/components/NotificationsBlock/components/MapPinNotification/index.tsx
  src/pages/NotificationsPage/components/NotificationsBlock/components/MapPinNotification/styles.ts
  src/pages/NotificationsPage/components/NotificationsBlock/components/NotificationsGroup/index.tsx
  src/pages/NotificationsPage/components/NotificationsBlock/components/NotificationsGroup/styles.ts
  src/pages/NotificationsPage/components/NotificationsBlock/components/RouteNotification/index.tsx
  src/pages/NotificationsPage/components/NotificationsBlock/components/RouteNotification/styles.ts
  src/pages/NotificationsPage/components/NotificationsBlock/index.tsx
  src/pages/NotificationsPage/components/NotificationsBlock/styles.ts
  src/pages/NotificationsPage/components/NotificationsBlock/useGetNotifications.ts
  src/pages/NotificationsPage/index.tsx
  src/pages/PickUpTheOrder/BoardingPass/BoardingPassVerificationPage/index.tsx
  src/pages/PickUpTheOrder/BoardingPass/IdentityVerification/components/CustomerInformBlock/styles.css
  src/pages/RouteDetails/styles.css
  src/redux/slices/unreadNotificationsSlice.ts
  src/redux/store.ts
  src/routes/router.tsx
  src/utils/createIdString.ts
  tsconfig.json
Labels: enhancement

#14 Feat/feailed reasons connect
  src/api/orderActions.ts
  src/components/Header/index.tsx
  src/constants/constants.ts
  src/constants/numbers.ts
  src/interfaces/FailedReason/index.ts
  src/pages/FailedReason/index.tsx
  src/pages/FailedReason/useFailedReason.ts
  src/pages/OrderDetails/index.tsx
  src/routes/router.tsx
  src/utils/i18n.ts
Labels: enhancement

#18 Feat/baggage record UI
  package-lock.json
  package.json
  src/api/baggageActions.ts
  src/assets/icons/image.svg
  src/assets/icons/upload.svg
  src/constants/constants.ts
  src/pages/BaggageCover/index.tsx
  src/pages/BaggageCover/styles.ts
  src/pages/BaggageRecord/index.tsx
  src/pages/BaggageRecord/styles.ts
  src/pages/BaggageRecord/useBaggageRecord.ts
  src/pages/RouteDetails/components/StatusIcon/index.tsx
  src/routes/router.tsx
  src/utils/i18n.ts
  src/utils/stringUtils.test.ts
  src/utils/stringUtils.ts
  tsconfig.node.json
Labels: enhancement

#34 chore: add prefix to commented code
  src/pages/BaggageRecord/useBaggageRecord.ts
Labels: documentation

#36 feat: added redirect to Google Maps
  src/components/NavigateButton/index.tsx
  src/components/NavigateButtonModal/index.tsx
  src/pages/RouteDetails/components/RouteActionButtons/index.tsx
  src/pages/RouteDetails/hooks/useFetchAndProcessRoute.ts
  src/pages/RouteDetails/hooks/useProcessAddresses.ts
  src/pages/RouteDetails/index.tsx
  src/redux/slices/routeSlice.ts
  src/utils/googleMapsUtils.test.ts
  src/utils/googleMapsUtils.ts
Labels: enhancement

#32 Feat/expiration modal mobile
  src/App.tsx
  src/components/TokenExpiredModal/index.tsx
  src/components/TokenExpiredModal/styles.ts
  src/components/TokenExpiredModal/useTokenExpiredModal.ts
  src/main.tsx
  src/pages/MainPage/index.tsx
  src/pages/VerificationPage/index.tsx
  src/pages/VerificationPage/useVerification.ts
  src/redux/slices/tokenModalSlice.ts
  src/redux/store.ts
  src/routes/router.tsx
  src/utils/axiosInstance.ts
  src/utils/i18n.ts
Labels: enhancement

#38 * Fix: TS build errors
  src/pages/OrderDetails/index.tsx
  src/pages/PersonalProfile/index.tsx
Labels: bug, invalid
