Repository ZenBit-Tech/Codecrafter_mobile, pull requests merged in 2025-01, with the labels that each got.

#42 Feat/scan code
  package-lock.json
  package.json
  src/assets/icons/warn-icon.svg
  src/constants/numbers.ts
  src/pages/BaggageCover/useBaggageCover.ts
  src/pages/PickUpTheOrder/ScanCode/components/ActionBtns/index.tsx
  src/pages/PickUpTheOrder/ScanCode/components/ActionBtns/styles.ts
  src/pages/PickUpTheOrder/ScanCode/components/InformBlock/index.tsx
  src/pages/PickUpTheOrder/ScanCode/components/InformBlock/styles.ts
  src/pages/PickUpTheOrder/ScanCode/index.tsx
  src/pages/PickUpTheOrder/ScanCode/styles.css
  src/pages/PickUpTheOrder/ScanCode/styles.ts
  src/pages/PickUpTheOrder/ScanCode/useScanLock.ts
  src/pages/PickUpTheOrder/SmartLockSecuredPage/components/ActionBtns/index.tsx
  src/pages/PickUpTheOrder/SmartLockSecuredPage/components/ActionBtns/styles.ts
  src/pages/PickUpTheOrder/SmartLockSecuredPage/index.tsx
  src/pages/PickUpTheOrder/SmartLockSecuredPage/styles.ts
  src/routes/router.tsx
Labels: enhancement

#40 Feat/store customer sign
  src/pages/OrderDetails/useGetOrderDetails.ts
  src/pages/PickUpTheOrder/BaggageCheck/CustomerConfirmation/components/ActionBtns/index.tsx
  src/pages/PickUpTheOrder/BaggageCheck/CustomerConfirmation/components/ActionBtns/styles.ts
  src/pages/PickUpTheOrder/BaggageCheck/CustomerConfirmation/components/CustomerConfirmationBlock/index.tsx
  src/pages/PickUpTheOrder/BaggageCheck/CustomerConfirmation/components/CustomerConfirmationBlock/styles.ts
  src/pages/PickUpTheOrder/BaggageCheck/CustomerConfirmation/index.tsx
  src/pages/PickUpTheOrder/BaggageCheck/CustomerConfirmation/useCustomerConfirm.ts
  src/redux/slices/currentCustomerIdSlice.ts
  src/redux/store.ts
Labels: enhancement, invalid

#44 feat: connected order details to GoogleMaps
  src/hooks/useGeocodeAddress.ts
  src/pages/OrderDetails/index.tsx
Labels: enhancement

#41 fix: fixed not correct displaying route detailes page after chenging …
  src/pages/RouteDetails/hooks/useFetchAndProcessRoute.ts
  src/pages/RoutesPage/components/RouteItem/index.tsx
  src/redux/slices/routeSlice.ts
Labels: bug, enhancement

#43 Feat/nav buttons
  src/constants/numbers.ts
  src/pages/OrderDetails/components/BottomNavigationBar/index.tsx
  src/pages/OrderDetails/components/BottomNavigationBar/useNavigateWithinRoute.ts
Labels: enhancement

#37 feat:Scrum 226 FE loader for login driver
  src/components/Button/index.tsx
  src/pages/SignIn/useSignIn.ts
  src/pages/VerificationPage/useVerification.ts
  src/redux/slices/authSlice.ts
Labels: bug, enhancement

#45 feat: add redirection after failed reason submission
  src/interfaces/FailedReason/index.ts
  src/pages/FailedReason/useFailedReason.ts
Labels: enhancement

#46 + Add: redirect logic
  src/App.tsx
  src/constants/styles.css
  src/pages/NotificationsPage/components/NotificationsBlock/components/ListOfNotes/index.tsx
  src/pages/NotificationsPage/components/NotificationsBlock/components/LuggageNotification/index.tsx
  src/pages/NotificationsPage/components/NotificationsBlock/components/MapPinNotification/index.tsx
  src/pages/NotificationsPage/components/NotificationsBlock/components/RouteNotification/index.tsx
Labels: enhancement

#47 fix: removed warning from useGeocodeAddress hook
  src/hooks/useGeocodeAddress.ts
Labels: bug, invalid

#49 + Create: custom map pin
  src/assets/icons/map-pin copy.svg
  src/components/CustomMapPin/index.tsx
  src/pages/RouteDetails/components/RoutingControl/index.tsx
  src/theme.ts
Labels: bug, enhancement, invalid

#52 + Update: Readme.md
  README.md
Labels: documentation

#51 Feat/storybook
  .eslintrc.cjs
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/components/Button/index.stories.tsx
Labels: documentation

#53 fix: fixed Route Map Modal Fails to Load Properly in the Driver App
  src/pages/RouteDetails/components/RoutingControl/index.tsx
Labels: bug, invalid
